spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://192.168.99.100:3306/
  jpa.hibernate.ddl-auto: create-drop

logging:
  level:
    root: WARN
    br.com.kimae.multitenacydemo: DEBUG
    com.mysql: NONE
